### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by badboycxcc** [nick-frischkorn/jordanspecial#2]
root@racknerd-1b245e:~/jordanspecial# python3 jordanspecial.py 
Traceback (most recent call last):
  File "jordanspecial.py", line 189, in <module>
    main()
  File "jordanspecial.py", line 39, in main
    args = parser.parse_args()
  File "/usr/lib/python3.7/argparse.py", line 1758, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1790, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1996, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.7/argparse.py", line 1936, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.7/argparse.py", line 1864, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.7/argparse.py", line 1046, in __call__
    parser.print_help()
  File "/usr/lib/python3.7/argparse.py", line 2483, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3.7/argparse.py", line 2467, in format_help
    return formatter.format_help()
  File "/usr/lib/python3.7/argparse.py", line 293, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python3.7/argparse.py", line 224, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.7/argparse.py", line 224, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.7/argparse.py", line 348, in _format_usage
    assert ' '.join(opt_parts) == opt_usage
AssertionError

**Comment by nick-frischkorn** [comment]
Posting an error from argparse without any other context is useless. Try including some more details.
